name = "viralstudio-db-proxy"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "viralstudio-db"
database_id = "e6f4d39c-9d4d-4570-8a3d-5aed60bd83b0"
